Document: lite-control-center
Title: Debian lite-control-center Manual
Author: <insert document author here>
Abstract: This manual describes what lite-control-center is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/lite-control-center/lite-control-center.sgml.gz

Format: postscript
Files: /usr/share/doc/lite-control-center/lite-control-center.ps.gz

Format: text
Files: /usr/share/doc/lite-control-center/lite-control-center.text.gz

Format: HTML
Index: /usr/share/doc/lite-control-center/html/index.html
Files: /usr/share/doc/lite-control-center/html/*.html
