#! /bin/sh

dpkg-scanpackages . /dev/null > Packages

gzip -9c Packages > Packages.gz

cat > Release <<EOF
Archive: precise
Origin: Linux Lite
Label: Linux Lite Repository
Architecture: i386 amd64
MD5Sum:
EOF
printf ' '$(md5sum Packages    | cut --delimiter=' ' --fields=1)' %16d Packages\n'  $(wc --bytes Packages    | cut --delimiter=' ' --fields=1) >> Release
printf ' '$(md5sum Packages.gz | cut --delimiter=' ' --fields=1)' %16d Packages.gz' $(wc --bytes Packages.gz | cut --delimiter=' ' --fields=1) >> Release

gpg --armor --detach-sign --output Release.gpg --yes Release

